#!/bin/bash

set -ex

# Check if amulet is installed before adding repository and updating apt-get.
if ! dpkg -s amulet; then
    sudo add-apt-repository -y ppa:juju/stable
    sudo apt-get update
    sudo apt-get install -y amulet
fi
