#!/usr/bin/env python3

from unittest import TestCase, main

from basic import (
    BasicDeploymentSpec,
    BasicDeploymentTest,
)


class TrustyBasicDeploymentTest(BasicDeploymentTest, TestCase):

    spec = BasicDeploymentSpec(series="trusty")


if __name__ == "__main__":
    main()
