#!/usr/bin/env python3

from unittest import TestCase, main

from website import (
    WebsiteDeploymentSpec,
    WebsiteDeploymentTest,
)


class TrustyWebsiteDeploymentTest(WebsiteDeploymentTest, TestCase):

    spec = WebsiteDeploymentSpec(series="trusty")


if __name__ == "__main__":
    main()
