#!/usr/bin/env python3

from unittest import TestCase, main

from website import (
    WebsiteDeploymentSpec,
    WebsiteDeploymentTest,
)


class XenialWebsiteDeploymentTest(WebsiteDeploymentTest, TestCase):

    spec = WebsiteDeploymentSpec(series="xenial", storage=False)


if __name__ == "__main__":
    main()
