#!/usr/bin/env python3

from unittest import TestCase, main

from slave import (
    SlaveDeploymentSpec,
    SlaveDeploymentTest,
)


class XenialSlaveDeploymentTest(SlaveDeploymentTest, TestCase):

    spec = SlaveDeploymentSpec(series="xenial")


if __name__ == "__main__":
    main()
