#!/usr/bin/env python3

from unittest import TestCase, main

from external import (
    ExternalDeploymentSpec,
    ExternalDeploymentTest,
)


class XenialExternalDeploymentTest(ExternalDeploymentTest, TestCase):

    spec = ExternalDeploymentSpec(series="xenial")


if __name__ == "__main__":
    main()
