#!/bin/bash

set -eu

# Install jenkins
install_jenkins () {
    ensemble-log "Installing jenkins..."
    apt-get -y install python-software-properties
    add-apt-repository ppa:hudson-ubuntu/testing
    add-apt-repository ppa:python-jenkins-developers/testing
    apt-get update
    apt-get -y install -qq jenkins jenkins-ssh-slaves-plugin
}
[[ -d /etc/init/jenkins.conf ]] || install_jenkins

# Install helpers  - python jenkins ++
install_python_jenkins () {
    ensemble-log "Installing python-jenkins..."
	# Pickup backports as required for natty
    add-apt-repository ppa:python-jenkins-developers/backports
    apt-get update
    apt-get -y install -qq python-jenkins
}
[[ -d /usr/share/pyshared/jenkins ]] || install_python_jenkins

# Install some tools - can get set up deployment time
install_tools () {
	ensemble-log "Installing tools..."
    apt-get -y install -qq `config-get tools`
}
install_tools 

ensemble-log "Opening ports"
open-port 8080

exit 0
