#!/bin/bash

set -ue

# Grab information that remote unit has posted to relation
slavehost=$(relation-get slavehost)
executors=$(relation-get executors)
labels=$(relation-get labels)

# Double check to see if this has happened yet
if [ "x$slavehost" = "x" ]; then
	juju-log "Slave host not yet defined, exiting..."
	exit 0
fi

juju-log "Adding slave with hostname $slavehost..."
$(dirname $0)/addnode $slavehost $executors "$labels"
juju-log "Node slave $slavehost added..."
