#!/bin/bash

set -ue

# Slave hostname is derived from unit name so
# this is pretty safe
slavehost=`echo $ENSEMBLE_REMOTE_UNIT | sed s,/,-,`

echo "Deleting slave with hostname $slavehost"
cd /opt/python-jenkins
python delnode.py $slavehost

exit 0
