#!/bin/bash

set -e


url=`relation-get url`

if [ "x$url" = "x" ]; then
	echo "master hasn't exported its url yet, exiting"
	exit 0
fi

cat > /etc/init/jenkins-slave.override << EOF
env JENKINS_URL=$url
EOF

stop jenkins-slave || /bin/true
start jenkins-slave

slavehost=`hostname`

relation-set slavehost=$slavehost
