#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
)
from charms.layer.jenkins.users import (
    AdminUserNotConfiguredException,
    Users,
)


def get_admin_password():
    users = Users()
    try:
        admin_password = users.get_admin_password()
        action_set({'password': admin_password})
    except AdminUserNotConfiguredException:
        action_fail("The admin user hasn't been configured yet, please try again later.")


try:
    get_admin_password()
except Exception as e:
    action_fail("Failed to get admin password: {}".format(str(e)))
