#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
)
from charms.layer.jenkins.credentials import Credentials


def get_admin_credentials():
    creds = Credentials()
    action_set({
        'username': creds.username,
        'password': creds.password,
    })


try:
    get_admin_credentials()
except Exception as e:
    action_fail("Failed to get admin credentials: {}".format(str(e)))
