#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    function_fail,
    function_set,
)

from charms.layer.jenkins.api import Api


def update_plugins():
    api = Api()
    api.check_update_center()
    plugins = api.get_updatable_plugins()
    if len(plugins) > 0:
        api.update_plugins()
        api.restart()
        function_set({'output': "Updated plugins: {}".format(plugins),
                      'outcome': 'Success'})
    else:
        function_set({'output': "No plugins available to be updated.",
                      'outcome': 'Success'})


try:
    update_plugins()
except Exception as e:
    function_fail("Failure: {}".format(str(e)))
