#!/usr/bin/env python3

import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charms.layer.jenkins.packages import Packages

packages = Packages()
packages.install_dependencies()
packages.install_jenkins()
