#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
)

import reactive.jenkins as Jenkins


def upgrade():
    Jenkins.upgrade_jenkins()
    action_set({'output': "Jenkins has been upgraded",
                'outcome': 'Success'})


try:
    upgrade()
except Exception as e:
    action_fail("Failed to upgrade jenkins: {}".format(str(e)))
