name: Integration Test

on:
  workflow_call:

jobs:
  integration-test-lxd:
    strategy:
      matrix:
        # ubuntu 18.04 is no longer supported and hence xenial cannot be tested.
        series: [bionic, focal]
        module: [agent, basic, nrpe, website]
      fail-fast: false
    name: Integration tests (lxd)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          charm-channel: 2.x/stable
      - name: Run integration tests
        run: |
          tox -e integration -- -k ${{ matrix.module }} --series ${{ matrix.series }}
