name: Scheduled Test

on:
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  integration-test:
    steps:
    - name: Integration tests (lxd)
      uses: ./.github/workflows/integration_test.yaml

    - name: Notify
      # TODO: `always()` for testing. Switch to `failure()`.
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v3
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: andrew.liaw@canonical.com
        # from email name
        from: ${{ secrets.EMAIL_USERNAME }}
