name: Scheduled Test

on:
  schedule:
    # Execute weekly on Monday UTC time. Offset time to avoid high load period on github servers.
    - cron: "15 3 * * 1"

jobs:
  integration-test:
    name: Integration tests (lxd)
    uses: ./.github/workflows/integration_test.yaml
  notify-on-run:
    name: Notify on run
    needs: [integration-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER_ADDR }}
          server_port: ${{ secrets.EMAIL_SERVER_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: is-devops-team@canonical.com
          subject: "[Scheduled Test] Jenkins Charm integration test ${{ github.repository }} has ${{ needs.integration-test.result }}"
          body: |
            Scheduled Jenkins Charm integration test of ${{ github.repository }} has ${{ needs.integration-test.result }}.
            Run ID: ${{ github.run_id}}
            Run Number: ${{ github.run_number }}
            Run Attempt: ${{ github.run_attempt}}
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}
