name: Scheduled Test

on:
  # TODO: Change back to schedule.
  pull_request:
  # schedule:
  #   # Execute weekly on Monday UTC time. Offset time to avoid high load period on github servers.
  #   - cron: "15 3 * * 1"

jobs:
  integration-test:
    name: Integration tests (lxd)
    uses: ./.github/workflows/integration_test.yaml
  notify-on-failure:
    name: Notify on failure
    needs: [integration-test]
    # TODO: Set to failure().
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check credential exists
        if: ${{ secrets.EMAIL_USERNAME == null || secrets.EMAIL_PASSWORD == null }}
        run: |
          echo "Missing email username and password as input for this workflow."
          exit 1
      - name: Notify Failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: is-devops-team@canonical.com
          subject: "[Scheduled Test] Jenkins Charm integration test ${{ github.repository }} has ${{ job.status }}"
          body: |
            Scheduled Jenkins Charm integration test of ${{ github.repository }} has ${{ job.status }}.
            Run ID: ${{ github.run_id}}
            Run Number: ${{ github.run_number }}
            Run Attempt: ${{ github.run_attempt}}
            URL: ${{ github.repositoryUrl }}
