name: Scheduled Test

on:
  schedule:
    - cron: "10 1 * * TUE"

jobs:
  integration-test:
    name: Integration tests (lxd)
    uses: ./.github/workflows/integration_test.yaml
    with:
      notify: true    
    secrets: inherit
